/**
 * Converts design records to Markdown for export and project spec.
 */
import type { DesignConfig } from "@/types/design";

export interface DesignRecordForExport {
  id: string;
  name: string;
  config: DesignConfig;
  created_at?: string;
  updated_at?: string;
}

export function designConfigToMarkdown(config: DesignConfig): string {
  const lines: string[] = [];

  lines.push(`# ${config.pageTitle} — Design Spec`);
  lines.push("");
  lines.push(`**Project:** ${config.projectName}`);
  lines.push(`**Template:** ${config.templateId}`);
  if (config.notes) {
    lines.push("");
    lines.push(config.notes);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("## Colors");
  lines.push("");
  lines.push("| Token | Hex |");
  lines.push("|-------|-----|");
  lines.push(`| Primary | \`${config.colors.primary}\` |`);
  lines.push(`| Secondary | \`${config.colors.secondary}\` |`);
  lines.push(`| Accent | \`${config.colors.accent}\` |`);
  lines.push(`| Background | \`${config.colors.background}\` |`);
  lines.push(`| Surface | \`${config.colors.surface}\` |`);
  lines.push(`| Text | \`${config.colors.text}\` |`);
  lines.push(`| Text (muted) | \`${config.colors.textMuted}\` |`);
  lines.push("");

  lines.push("## Typography");
  lines.push("");
  lines.push(`- **Heading font:** ${config.typography.headingFont}`);
  lines.push(`- **Body font:** ${config.typography.bodyFont}`);
  lines.push(`- **Base size:** ${config.typography.baseSize}`);
  lines.push(`- **Scale:** ${config.typography.scale}`);
  lines.push("");

  lines.push("## Layout");
  lines.push("");
  lines.push(`- **Max width:** ${config.layout.maxWidth}`);
  lines.push(`- **Spacing:** ${config.layout.spacing}`);
  lines.push(`- **Border radius:** ${config.layout.borderRadius}`);
  lines.push(`- **Nav style:** ${config.layout.navStyle}`);
  lines.push("");

  lines.push("## Page Structure (Sections)");
  lines.push("");
  const sorted = [...config.sections].filter((s) => s.enabled).sort((a, b) => a.order - b.order);
  sorted.forEach((s, i) => {
    lines.push(`${i + 1}. **${s.title}** (\`${s.kind}\`)`);
    if (s.description) lines.push(`   - ${s.description}`);
    if (s.copy) lines.push(`   - Copy: ${s.copy}`);
    lines.push("");
  });

  lines.push("---");
  lines.push("");
  lines.push("*Generated by Design Configurator*");

  return lines.join("\n");
}

/** Full design record to .md for Project Spec export. */
export function designRecordToMarkdown(record: DesignRecordForExport): string {
  const lines: string[] = [];
  lines.push(`# ${record.name}`);
  lines.push("");
  lines.push(`- **ID:** \`${record.id}\``);
  if (record.created_at) lines.push(`- **Created:** ${record.created_at}`);
  if (record.updated_at) lines.push(`- **Updated:** ${record.updated_at}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(designConfigToMarkdown(record.config));
  return lines.join("\n");
}
